//v112 (c) 2008-2015 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
"undefined"==typeof Tynt.TIL&&"undefined"==typeof Tynt.TCL&&function(){var e=window,f=document,m={distro:"TC-"+(new Date).getTime()};Tynt.TCL=function(){function G(a){var c=G.options;a=c.parser[c.strictMode?"strict":"loose"].exec(a);for(var b={},d=14;d--;)b[c.key[d]]=a[d]||"";b[c.q.name]={};b[c.key[12]].replace(c.q.parser,function(a,d,g){d&&(b[c.q.name][d]=g)});return b}if(document.body){Date.now||(Date.now=function(){return(new Date).getTime()});var h={_icUrl:"http://"+(Tynt.e||"")+"ic.tynt.com",
_debUrl:"http://"+(Tynt.e||"")+"de.tynt.com/deb/v2",_sicUrl:"http://"+(Tynt.e||"")+"sic-akamai.33across.com/1/javascripts/sic.js",_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",newEle:function(a,c,b,d){d=d||window;a=d.document.createElement(a);c&&this.extend(a,c);b&&this.extend(a.style,b);return a},injectScript:function(a,c){var b,d;c=c||window;d=this.newEle("script",{async:"async",type:"text/javascript",src:a},null,c);b=c.document.getElementsByTagName("script")[0];b.parentNode.insertBefore(d,
b)},injectSicScript:function(){this.injectScript(this._sicUrl)},injectSicIframe:function(a,c){var b;b=this.newEle("iframe",{src:"about:blank",frameBorder:"0",frameSpacing:"0",scrolling:"no"},{width:c.width+"px",height:c.height+"px",border:"0 none",margin:"0"});a?"script"==a.tagName.toLowerCase()?a.parentNode.insertBefore(b,a):a.appendChild(b):document.body.appendChild(b);c.sicWindow=b.contentWindow;b=b.contentWindow.document;b.open();b.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+
this._sicUrl+'">\x3c/script></body></html>');b.close()},injectPixel:function(a,c,b){var d;try{d=f.createElement("img")}catch(e){d=document.createElement("img")}d&&(c&&(d.onload=c),b&&(d.onerror=b),d.src=a)},docUrl:function(){var a,c=null,b;b=f.getElementsByTagName("link");for(a=0;a<b.length;++a)b[a].getAttribute("href")&&b[a].getAttribute("rel")&&0<=b[a].getAttribute("rel").indexOf("canonical")&&(c=b[a].href);if(!c)for(b=f.getElementsByTagName("meta"),a=0;a<b.length;++a)"og:url"===b[a].getAttribute("property")&&
b[a].getAttribute("content")&&(c=b[a].getAttribute("content"));if(!c)for(a=0;a<b.length;++a)"original-source"===b[a].getAttribute("name")&&b[a].getAttribute("content")&&(c=b[a].getAttribute("content"));return c?(0!=c.indexOf("http")&&(a=e.location.protocol+"//"+e.location.host+e.location.pathname,(b=f.getElementsByTagName("base")[0])&&(b=b.getAttribute("href"))&&(a=b),"/"==c.charAt(0)?(b=a.indexOf("/",9),-1<b&&(a=a.slice(0,b))):(b=a.lastIndexOf("/"),a=9<b?a.slice(0,b+1):a+"/"),c=a+c),c):""},extend:function(a,
c){var b,d;for(b=1;b<arguments.length;++b)for(d in arguments[b])arguments[b].hasOwnProperty(d)&&(a[d]=arguments[b][d]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===Object.prototype.toString.call(a)},inArray:function(a,c){return 0<=this.indexOf(a,c)},indexOf:function(a,c){if(a.indexOf)return a.indexOf(c);for(var b=0;b<a.length;++b)if(a[b]===c)return b;return-1},unique:function(a){var c,b={},d=[];for(c=0;c<a.length;++c)b[a[c]]||(b[a[c]]=!0,d.push(a[c]));return d},iframeType:function(){var a=
null,c=0;try{a=window.frameElement}catch(b){}if(a)a.id&&0<=a.id.search(/google_ads?_i?frame/)?(c=6,h.log(m.distro,"In same-origin iframe from DFP")):(c=5,h.log(m.distro,"In same-origin iframe"));else try{window!=window.top?"undefined"!=typeof window.$sf?(c=4,h.log(m.distro,"In SafeFrame")):(c=3,h.log(m.distro,"In cross-origin iframe")):h.log(m.distro,"In top window")}catch(d){c=3,h.log(m.distro,"DEBUG: exception 2")}return c},getTopWin:function(){var a=window;try{for(;a.parent!==a&&a.parent.document;)a=
a.parent}catch(c){}return a},jsonDecode:function(a){if("function"!==typeof Array.prototype.toJSON)return JSON.stringify(a);var c=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=c;return a},getCookie:function(a,c){for(var b=c+"=",d=a.split(";"),e=0;e<d.length;e++){for(var k=d[e];" "==k.charAt(0);)k=k.substring(1,k.length);if(0===k.indexOf(b))return k.substring(b.length,k.length)}return null},rmScheme:function(a){return a.replace(/^https?:\/\//,"")},trim:function(a){return a.replace(/^\s+|\s+$/g,
"")},tyntIds:function(){return this.unique(Tynt).join("~")},log:function(){"undefined"==typeof Tynt.debug&&(Tynt.debug=0<e.location.search.indexOf("__tcdebugmode=1")?1:0);1===Tynt.debug&&e.console&&e.console.log&&e.console.log.apply(e.console,arguments)},callIc:function(){var a,c,b,d,D,k,g;e._33Across.state.icDone||(e._33Across.state.icDone=1,a=this.trim((f.title||e.location.hostname).toString()).replace(new RegExp(e.location.hash,"g"),""),c=this.getCookie(f.cookie,"tracertraffic"),b=encodeURIComponent(this.rmScheme(this.docUrl())),
d=e.location.hash,d=/tynt=/.test(d)?d.match(/tynt=?([^?&$#]*)/)[1]:!1,D=this._icUrl+"/b/p?id="+this.tyntIds()+(c?"&et="+c:"")+(d?"&a="+d:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+m.type+"&ts="+Date.now(),k=D+(b?"&cu="+b:""),g=k+(f.referrer?"&r="+encodeURIComponent(this.rmScheme(f.referrer)):""),a=g+"&t="+encodeURIComponent(a),this.log(m.distro,"Calling IC"),h.callIc.rsp=function(){e._33Across.state.icDone=2},this.injectPixel(a,h.callIc.rsp,function(){h.injectPixel(g,h.callIc.rsp,function(){h.injectPixel(k,
h.callIc.rsp,function(){h.injectPixel(D,h.callIc.rsp)})})}))},callDeb:function(a){if("undefined"==typeof a){if(e._33Across.state.deDone)return;a=4}e._33Across.state.deDone=!0;0==a||2==e._33Across.state.icDone?(this.log(m.distro,"Calling DEB"+(0==a?" on IC timeout":"")),this.injectScript(this._debUrl+"?id="+this.tyntIds()+"&r="+encodeURIComponent(this.rmScheme(f.referrer)),e)):setTimeout(function(){h.callDeb(a-1)},50)}};m.type=h.iframeType();5<=m.type&&(e=h.getTopWin(),f=e.document);e._33Across||(e._33Across=
{});e._33Across.state||(e._33Across.state={icDone:0,deDone:!1,ivDone:!1});G.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};
var l=f.body,n=f.documentElement,Q=e.eval("/*@cc_on!@*/false"),H=function(a,c){for(var b="",d=0;d<c;d++)b+=a;return b},A=H("a",50),z=(Tynt.e||"")+"ic.tynt.com",I=z+"/b/s",J;J=e.addEventListener?function(a,c,b){a.addEventListener(c,b,!1)}:function(a,c,b){a.attachEvent("on"+c,b)};var R=function(a){"complete"==f.readyState?a():J(e,"load",function(c){setTimeout(function(){"undefined"!=typeof f.readyState||Q||(f.readyState="complete");a()},10)})},v=function(a,c){var b=[],d=function(a,b){var c="http://"+
a.replace("id="+A,"id="+h.tyntIds());-1<c.indexOf(z+"/b/p?")&&"string"==typeof Tynt.b&&(c+="&b="+Tynt.b);var d=new Image(1,1);b&&(d.onerror=b);d.src=c};v=function(a,c){b.push([a,c])};R(function(){v=d;for(var a=0;a<b.length;a++)v(b[a][0],b[a][1]);b=null});v(a,c)},K=function(a){var c=[],b="",d;for(d in a)a.hasOwnProperty(d)&&(c.push(b,d,"=",a[d]),b="&");return c.join("")},M=function(a){for(var c=0,b=100>a.length?a.length:100,d=0;d<b;d++)c+=a.charCodeAt(d);a=Math.floor(3844*Math.random());b=Math.abs(Date.now()-
12281184E5);return L(b,7)+L((c+a)%3844,2)},N=function(a){if(62>a)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);var c=Math.floor(a/62);a-=62*c;return 62<=c?N(c)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(c)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)},L=function(a,c){var b=N(a);return H("0",c-b.length)+b},S=h.trim((f.title||e.location.hostname).toString()).replace(new RegExp(e.location.hash,
"g"),""),y=function(a){return a.replace(/^https?:\/\//,"")},T=function(){if(-1!==f.cookie.indexOf("tracertraffic=")&&(!f.referrer||-1==f.referrer.indexOf(e.location.host))){var a=e.location.hostname.split("."),c,b=2;do c="tracertraffic=0;path=/;domain=."+a.slice(a.length-b,a.length).join(".")+";expires=Thu, 01 Jan 1970 00:00:00 GMT",f.cookie=c,b++;while(-1==f.cookie.indexOf("tracertraffic=0")&&b<=a.length);-1==f.cookie.indexOf("tracertraffic=0")&&(f.cookie="tracertraffic=0;path=/;expires=Thu, 01 Jan 1970 00:00:00 GMT")}},
q=function(){var a=[];return function(c){for(var b=a.length-1;0<=b;b--)if(a[b]==c)return!1;a.unshift(c);3<a.length&&a.pop();return!0}},U=q(),V=q(),W=function(a){var c,b=function(a){e.removeEventListener("blur",b,!1);E(c);return!0};return function(a){c=a.target||a.srcElement;e.removeEventListener("blur",b,!1);"IMG"==c.nodeName&&"A"!=c.parentNode.nodeName&&(e.addEventListener("blur",b,!1),setTimeout(function(){f.removeEventListener("blur",b,!1)},1E4));return!0}}(),O=function(a){E(a.target||a.srcElement,
!0)},u,P=function(a){a=a.target||a.srcElement;u="IMG"==a.nodeName?a:null},F=function(a){var c=function(a){return"number"==typeof a.pageX?{x:a.pageX-(n.scrollLeft?n.scrollLeft:l.scrollLeft),y:a.pageY-(n.scrollTop?n.scrollTop:l.scrollTop)}:{x:a.clientX,y:a.clientY}},b=function(a){a=c(a);return 0>=a.x||0>=a.y||a.x>=l.clientWidth||a.y>=l.clientHeight},d=function(a){a=c(a);return 0>=a.x||0>=a.y||a.x>=n.clientWidth||a.y>=n.clientHeight},e=function(a){return"#document"==a.target.nodeName},k=function(a){a=
c(a);return 4>=a.x||4>=a.y||a.x>=n.clientWidth-4||a.y>=n.clientHeight-4},g=function(a){g=navigator.userAgent.match("MSIE")?f.compatMode&&-1!=f.compatMode.indexOf("CSS")?d:b:navigator.userAgent.match("Firefox")?e:k;g(a)};return function(a){u&&g(a)&&(E(u),u=null);return!0}}();Tynt.ci=function(){var a;return function(c,b){a=b||a;var d=I+["?ci=",c,"&id=",A,"&g=",a,"&r=",encodeURIComponent(y(f.referrer)),"&ts=",Date.now()].join("");v(d)}}();Tynt.st=function(){var a;return function(c,b,d,h){a=d||a;c=[I,
"?",encodeURIComponent(c),"=",encodeURIComponent(b),"&id=",A,"&g=",a,"&r=",encodeURIComponent(y(f.referrer)),"&href=",encodeURIComponent(y(e.location.href)),"&ts=",Date.now()];b="";if(h){b=[];d="";for(var k in h)h.hasOwnProperty(k)&&(b.push(d,encodeURIComponent(k),"=",encodeURIComponent(h[k])),d="&");b="&"+b.join("")}v(c.join("")+b)}}();Tynt.c?q=function(){}:(Tynt.c=!0,Tynt.m=Tynt.m||[],Tynt.n=Tynt.n||[],q=function(){var a=!0,c,b=function(b,c){var e;e=(e=h.trim(c))?e.split(/\s+/i).length:0;var g=
{id:A,wc:e,c:c,f:a?1:0,t:S};h.extend(g,b);a=!1;e=g.trace_type;delete g.trace_type;var f=g.g;delete g.g;for(var p=[],t="id wc f w h t c".split(" "),m=0;m<t.length;m++){var n=t[m],l=g[n];l&&p.push([n,encodeURIComponent(l).replace(/\'/g,"%27")]);delete g[n]}for(var r in g)g.hasOwnProperty(r)&&(t=g[r])&&p.push([r,encodeURIComponent(t).replace(/\'/g,"%27")]);r=[];var m=2048-(("http://"+z+"/a/t/x#?").length+(3+f.length)+5),n=p.length,w=l=0,x=0,q,u,y,B,C=0;for(r[C]={g:f,tp:null};l<n&&35>r.length;)q=p[l][0],
g=p[l][1],y=q.length+2,u=m-y-w,0<u?(t=g.substring(x,x+u),B=t.slice(-2).indexOf("%"),-1<B&&(t=g.substring(x,x+u-2+B),w+=B+2),w+=t.length+y,x+=t.length,r[C][q]=t):w=m,w>=m&&(r[++C]={g:f,p:C},w=0),x>=g.length&&(l++,x=0);r[0].tp=r.length;v(z+"/b/t/"+e+"?"+K(r[0]));for(f=1;f<r.length;f++)v(z+"/b/x/"+e+"?"+K(r[f]))};e.addEventListener?(navigator.userAgent.match(/Firefox\/2\b/)||l.addEventListener("copy",O,!1),e.addEventListener("mousedown",P,!1),e.addEventListener("dragleave",F,!1),e.addEventListener("dragexit",
F,!1),f.addEventListener("contextmenu",W,!1)):(l.attachEvent("oncopy",O),f.getElementsByTagName("html")[0].attachEvent("ondragleave",F),l.attachEvent("onmousedown",P));T();h.callIc();h.callDeb();return function(a,m){if(!f.getElementById("tyntSh")){var k,g,l;m&&(f.selection&&f.selection.createRange?(g=f.selection.createRange(),l=g.duplicate(),k=g.text):(g=e.getSelection(),l=0<g.rangeCount&&g.getRangeAt(0),k=g.toString()));var p=a.src;if(p&&!k&&V(p)){g={trace_type:3,g:M(p),w:a.width,h:a.height};for(l=
0;l<Tynt.n.length;l++)Tynt.n[l](g,p);b(g,p)}else if(k&&h.trim(k).length&&"TEXTAREA"!=a.nodeName&&"INPUT"!=a.nodeName){p=U(k);g={trace_type:1};p&&(c=M(k));g.g=c;for(var n=!0,q=0;q<Tynt.m.length;q++)n=n&&Tynt.m[q](g,k,l,p);p&&n&&b(g,k)}}}});if(!/tracer=test|tracer=no_tracing|disableTracer=/.test(e.location.href)&&!/disableTracer=y/.test(f.cookie))var E=q()}else setTimeout(function(){Tynt.TCL()},62)};Tynt.TCL()}();
